### ISSUE TITLE
Make it work as a polyfill?

### ISSUE THREAD

**Issue by nuxodin** [johanholmerin/structured-clone#1]
Now that structuredClone has been specified as a global function, would it be safe and useful to expose structuredClone on the window-object inside this script?

https://html.spec.whatwg.org/multipage/structured-data.html#structured-cloning

I did some research and it seems to me that this script is the best polyfill for this.

**Comment by nuxodin** [comment]
I made a fork, exposing structuredClone as global.
https://github.com/nuxodin/structured-clone

Your script seems to work great!

**Comment by johanholmerin** [comment]
The goal is to provide a spec-compliant structured clone implementation, since there didn't seem to exist one. There are however some differences. As listed in the limitations in the README, there is no support for the transfer parameter. I don't think that is something that could be implemented in user-space.

I would **strongly** recommend against publishing a package that exposes this globally. There are [known](https://ponyfill.com/#how-are-ponyfills-better-than-polyfills) [issues](https://github.com/jonathantneal/document-promises/issues/4) with doing so. If a user needs that behavior, they can do so themselves.

**Comment by nuxodin** [comment]
Thank you for your reply.
Regarding the known issues, I think a polyfill is justified if the apis are ready standardized and it is spec-compiliant, although not complete.

**Comment by johanholmerin** [comment]
I would still encourage only distributing the package as a module. If end-users then decide to attach it to the global, thats up to them.

On a practical note, if you wish to continue to publish your package, it would be better to have this package as a dependency instead of forking, since otherwise you will have to keep downstreaming changes. All you need to do is:

```javascript
import structuredClone from '@johanholmerin/structured-clone';
globalThis.structuredClone = structuredClone;
```

Again, this is very simple, which is why I would discourage publishing it.

**Comment by nuxodin** [comment]
I agree with you this would be better, that's why I asked you :)

But i want to use this polyfill in my small polyfill service "lazyfill" (for
prototyping).
This one works with blocking xhr requests.
And therefore this approach is not practical.

https://github.com/nuxodin/lazyfill
